#!/bin/fish

clear

function DEBUG
    for i in (seq 0 100)
        Printgage $i DEBUG
        sleep 1
    end
    exit 0
end

function Printgage
    if test (count $argv) = 2
    and test $argv[2] = DEBUG
        echo "math $argv[1] / 4 = $(math $argv[1] / 4)"
        echo "math 25 - (math $argv[1] / 4) = $(math 25 - (math $argv[1] / 4))"
        echo "math \"ceil(\$(math $argv[1] / 4))\" = $(math "floor($(math $argv[1] / 4))")"
        echo "math 25 - (math \"ceil(\$(math $argv[1] / 4))\") = $(math 25 - (math "floor($(math $argv[1] / 4))"))"
        return 0
    end

    echo -n '['
    for i in (seq (math "floor($argv[1] / 4)"))
        echo -n '#'
    end
    for i in (seq (math "25 - floor($argv[1] / 4)"))
        echo -n .
    end
    echo -n "  $argv[1]%]"

    return 0
end

set n 0

if test (count $argv) != 0
and string match -rq '^[+-]?[0-9]+(\.[0-9]+)?$' -- $argv[1]
    set n $argv[1]
else
    set n 3
end

if test (count $argv) != 0
and test $argv[1] = DEBUG
    if test (count $argv) -gt 1
    and string match -rq '^[+-]?[0-9]+(\.[0-9]+)?$' -- $argv[2]
        set n $argv[2]
    end

    DEBUG
end

for i in (seq 0 100)
    echo -ne "time slipping...   energy usage: $(math "58000000 x ($i ^ 3)" | numfmt --to=si)Wh\t\t\t"
    Printgage $i
    echo
    test $i = 100 && break
    sleep $n
end

echo

set start_time (date +%s.%N)  # 秒＋ナノ秒
set duration 10

echo -n "@b@i@u@s@(blink)@(yellow)" | atansi
while test (math "$(date +%s.%N) - $start_time") -lt $duration
    echo -n "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
end
echo -n "@0" | atansi

echo
echo
echo "time slipping finished."
